socket_server:
  ip: "127.0.0.1"
  port: 9000

web_server:
  ip: "127.0.0.1"
  port: 8080

topics:
  - name: default_broadcast
    mode: broadcast
  
  - name: default_queue
    mode: queue

queue_settings:
  ack_mode_default: manual
  ack_timeout_ms: 60000
  auto_ack_delay_ms: 30000
